## Default configuration for papilotte
# Each value can be overriden in a custom config file, an environment
# variable (NOT IMPLEMENTED YET) or via command line argument 
# (see papilotte run --help)

# --- server ----------------------------------
port: 5000
host: localhost
debug: false


# --- logging ---------------------------------
log_level: info
# Set one or more space separated values from: console, file, syslog
log_handlers: console
# Only required for 'file' log handler
log_file: NULL

    
# --- api -------------------------------------
compliance_level: 1

# use a custum spec file (path to file)
spec_file: NULL

# overrides base path from spec (/api)
base_path: NULL

# This is the max value for size= param
max_size: 200

# IPIF allows usage of additional properties in objects 
# (so properties not defined in the spec)
# if strict_validation is set to true, usage of additional properties will
# raise a validation error, which might be helpful to dedect eg. typos
strict_validation: false

# Set this to true to make papilotte validate responses against the schema
validate_responses: false



# --- connector --------------------------------
connector: papilotte.connectors.mock


# --- metadata ---------------------------------
description: Short description of the data the service provides
provider: Name of the individual or institution running the service
contact: contact@example.com
formats:
    - application/json

# --- connector.json ---------------------------
# This paramater is only used from papilotte.connectors.json
# Point this parameter to the jason file you want to serve
json_file: /var/lib/papilotte/data.json